### ISSUE TITLE
TypeError: create is not a function

### ISSUE THREAD

**Issue by timoisalive** [RenaudRohlinger/r3f-perf#49]
I'm running into this error only by adding the `<Perf />` component.

My project is also using `zustand`, could there be some conflict or something...?

```
store.js:11 Uncaught TypeError: create is not a function
    at ./node_modules/r3f-perf/dist/store.js (store.js:11:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/r3f-perf/dist/index.js (index.js:3:15)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
...
```

**Comment by EpleyWebServices** [comment]
Getting the same error in the `store.js` file, because the `create` function is a named export from zustand, but is currently being imported as the default.
